
export const products = [
    {
    id:1,
    photo:"https://example.com/photo.jpg",
    name:"Земельный участок",
    message:"Определение победителя, состоялся",
    tradeType:"Аренда и продажа земельных участков",
    area:"1000 кв.м",
    description:"Очень красивый участок с видом на горы",
    cadastralNumber:"123456789",
    landUseType:"Личное подсобное хозяйство",
    startingPrice:500000,
    finalPrice:"700000",
    biddingEnd:"23 апреля 2023 г. 18:00",
    },
    {
    id:2,
    photo:"https://example.com/photo2.jpg",
    name:"Квартира в центре города",
    message:"Снижение цены!",
    tradeType:"Продажа недвижимости",
    area:"70 кв.м",
    description:"Уютная квартира в историческом центре города с видом на набережную",
    cadastralNumber:"987654321",
    propertyType:"Квартира",
    numberOfRooms:2,
    floor:"5/10",
    startingPrice:3000000,
    finalPrice:"2500000",
    biddingEnd:"31 мая 2023 г. 12:00",
    },
    {
    id:3,
    photo:"https://example.com/photo3.jpg",
    name:"Загородный дом с бассейном",
    message:"Новый объект!",
    tradeType:"Аренда недвижимости",
    area:"250 кв.м",
    description:"Просторный загородный дом с большим участком и бассейном в окружении природы",
    cadastralNumber:"2468101214",
    propertyType:"Дом",
    numberOfRooms:4,
    floor:"2",
    startingPrice:150000,
    finalPrice:"130000",
    biddingEnd:"15 июня 2023 г. 18:00",
    },
  ];